# Aumenta o tempo de espera para downloads (pode ser útil com redes lentas)
httpTimeout: 1000000000

# Cache local para evitar re-download de pacotes
enableGlobalCache: true

# Reutiliza o lockfile com segurança (evita conflitos esquisitos)
enableImmutableInstalls: true

# Evita prompts interativos em CI/CD
enableTelemetry: false

# Permite instalar mesmo se não tiver yarn.lock (útil pra automação)
defaultSemverRangePrefix: "^"

# Controla onde o cache é armazenado
# cacheFolder: .yarn/.cache

# Usa o mirror do Yarn para acelerar instalações (pode ativar se quiser)
# npmRegistryServer: "https://registry.yarnpkg.com"

# Salva logs mais detalhados (ajuda a debug em builds/CI)
logLevel: info

# Usa modo de plug-and-play (desativado por padrão, mas se ativar precisa configurar o projeto pra isso)
# nodeLinker: node-modules
