const SOCKET_RIDE = 'ride'
const SOCKET_ERROR = 'error'
const SOCKET_CONNECT = 'connect'
const SOCKET_DISCONNECT = 'disconnect'
const SOCKET_NOTIFICATION = 'notification'
const SOCKET_CONNECT_ERROR = 'connect_error'
const SOCKET_JOIN_NOTIFICATION = 'join_notification'
const SOCKET_NOTIFICATION_HISTORY = 'notification_history'

export {
  SOCKET_RIDE,
  SOCKET_ERROR,
  SOCKET_CONNECT,
  SOCKET_DISCONNECT,
  SOCKET_NOTIFICATION,
  SOCKET_CONNECT_ERROR,
  SOCKET_JOIN_NOTIFICATION,
  SOCKET_NOTIFICATION_HISTORY
}
